### ISSUE TITLE
Show version info in command line

### ISSUE THREAD

**Issue by TuulaP** [UB-Mannheim/ocr-fileformat#87] opened 2019-04-25 17:06 UTC
In order to add the software versions in use to the documentation of a project, it would be nice if e.g. the usage help of ocr-transform would also show the version information of the software itself.

(I'll keep searching if I can find it somewhere hidden).  Thank you!

**Comment by stweil** [comment] 2019-12-30 16:51
@TuulaP, the command line now supported `--version` to show the software version.
Can we close this issue?

**Comment by zuphilip** [comment] 2019-12-30 21:00
Oh, yes let us close it now. I can confirm that it works for me.

@TuulaP If the problem remains, then feel free to reopen it.

**Closed by zuphilip** 2019-12-30 21:00 UTC
Labels: enhancement
